FROM node:20 AS build
WORKDIR /web
COPY web/package.json web/package-lock.json* ./
RUN npm install
COPY web .
RUN npm run build
FROM nginx:stable-alpine
COPY --from=build /web/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx","-g","daemon off;"]
